CREATE SEQUENCE  "IREM"."PK_SEQ_UYRUK"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 27 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "IREM"."PK_SEQ_ILETISIM"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 6 CACHE 20 NOORDER  NOCYCLE ;
